# Generated by Django 2.2.5 on 2019-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypt', models.CharField(blank=True, max_length=10000)),
                ('input_file', models.FileField(blank=True, upload_to='')),
                ('test_feild', models.CharField(blank=True, max_length=10000)),
                ('state_check', models.IntegerField()),
            ],
        ),
    ]
