# Generated by Django 2.2.5 on 2019-12-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191217_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='state_check',
            field=models.CharField(default='Created', max_length=10000),
        ),
    ]
