# Generated by Django 2.2.5 on 2019-12-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191217_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='encrypt',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
